export const LoginActionTypes = {
    REQUEST_POSTS : 'REQUEST_POSTS',
    RECEIVE_USER_INFO : 'RECEIVE_USER_INFO',
    RECEIVE_LOGIN_AUTHENTICATION : 'RECEIVE_LOGIN_AUTHENTICATION',
    INVALIDATE_LOGIN_CHECK : 'INVALIDATE_LOGIN_CHECK',


}

export const ServerActionTypes = {
    REQUEST_FETCH_API : "REQUEST_FETCH_API",
    GET_SERVER_LIST : "GET_SERVER_LIST",
    STORE_SERVER_LIST : "STORE_SERVER_LIST",

    TOGGLE_CREATE_SERVER_MODAL: "TOGGLE_CREATE_SERVER_MODAL",
    TOGGLE_INFORMATION_MODAL: "TOGGLE_INFORMATION_MODAL",

    STORE_CURRENT_SELECTED_SERVER: "STORE_CURRENT_SELECTED_SERVER",
    STORE_SERVER_MASTER_LIST: "STORE_SERVER_MASTER_LIST",
    
    CREATE_NEW_SERVER: "CREATE_NEW_SERVER",
    COUNT: "COUNT",
    
    APPLICATION_TEST: "APPLICATION_TEST",
    

}