export const LoginActionTypes = {
  REQUEST_POSTS: "REQUEST_POSTS",
  RECEIVE_USER_INFO: "RECEIVE_USER_INFO",
  RECEIVE_LOGIN_AUTHENTICATION: "RECEIVE_LOGIN_AUTHENTICATION",
  INVALIDATE_LOGIN_CHECK: "INVALIDATE_LOGIN_CHECK",
  CONFIRM_LOGIN_STATUS: "CONFIRM_LOGIN_STATUS",
  STORE_LOGIN_INFORMATION: "STORE_LOGIN_INFORMATION",
  REQUEST_FETCH_API: "REQUEST_FETCH_API"

};

export const ServerActionTypes = {
  REQUEST_FETCH_API: "REQUEST_FETCH_API",
  GET_SERVER_LIST: "GET_SERVER_LIST",
  STORE_SERVER_LIST: "STORE_SERVER_LIST",

  TOGGLE_CREATE_SERVER_MODAL: "TOGGLE_CREATE_SERVER_MODAL",
  TOGGLE_INFORMATION_MODAL: "TOGGLE_INFORMATION_MODAL",

  STORE_CURRENT_SELECTED_SERVER: "STORE_CURRENT_SELECTED_SERVER",
  STORE_SERVER_MASTER_LIST: "STORE_SERVER_MASTER_LIST",


  COUNT: "COUNT",

  APPLICATION_TEST: "APPLICATION_TEST",

  //  CRUD
  CREATE_NEW_SERVER: "CREATE_NEW_SERVER",
  UPDATE_SERVER_GENERAL_INFORMATION: "UPDATE_SERVER_GENERAL_INFORMATION",
  UPDATE_SERVER_DETAIL: "UPDATE_SERVER_DETAIL",
  UPDATE_SERVER_ACCOUNT: "UPDATE_SERVER_ACCOUNT",
  UPDATE_SERVER_STATUS: "UPDATE_SERVER_STATUS",


};

export const ApplicationActionTypes = {
  REQUEST_FETCH_API: "REQUEST_FETCH_API",
  GET_APPLICATION_LIST: "GET_APPLICATION_LIST",
  STORE_APPLICATION_LIST: "STORE_APPLICATION_LIST",

  TOGGLE_CREATE_APPLICATION_MODAL: "TOGGLE_CREATE_APPLICATION_MODAL",
  TOGGLE_INFORMATION_MODAL: "TOGGLE_INFORMATION_MODAL",

  STORE_CURRENT_SELECTED_APPLICATION: "STORE_CURRENT_SELECTED_APPLICATION",

  CREATE_NEW_APPLICATION: "CREATE_NEW_APPLICATION",
  COUNT: "COUNT",

  //  CRUD
  APPLICATION_TEST: "APPLICATION_TEST",
  UPDATE_APPLICATION_INFORMATION: "UPDATE_APPLICATION_INFORMATION",
  UPDATE_APPLICATION: "UPDATE_APPLICATION",
  UPDATE_APPLICATION_STATUS: "UPDATE_APPLICATION_STATUS",


};

export const RepoActionTypes = {
  REQUEST_FETCH_API: "REQUEST_FETCH_API",
  GET_REPO_LIST: "GET_REPO_LIST",
  STORE_REPO_LIST: "STORE_REPO_LIST",

  CREATE_NEW_REPO: "CREATE_NEW_REPO",
  DELETE_REPO: "DELETE_REPO",
}

export const SystemActionTypes = {
  REQUEST_FETCH_API: "REQUEST_FETCH_API",
  GET_SYSTEM_LIST: "GET_SYSTEM_LIST",
  STORE_SYSTEM_LIST: "STORE_SYSTEM_LIST",

  CREATE_NEW_SYSTEM: "CREATE_NEW_SYSTEM",
  DELETE_SYSTEM: "DELETE_SYSTEM",
}

export const LogActionTypes = {
  REQUEST_FETCH_API: "REQUEST_FETCH_API",
  GET_LOG_LIST: "GET_LOG_LIST",
  STORE_LOG_LIST: "STORE_LOG_LIST",
  TOGGLE_CREATE_LOG_MODAL: "TOGGLE_CREATE_LOG_MODAL",
  CREATE_NEW_LOG: "CREATE_NEW_LOG",
  UPDATE_LOG_STATUS: "UPDATE_LOG_STATUS",
}

export const ApplicationInstanceActionTypes = {
  REQUEST_FETCH_API: "REQUEST_FETCH_API",
  GET_APPLICATION_INSTANCE_LIST: "GET_APPLICATION_INSTANCE_LIST",
  STORE_APPLICATION_INSTANCE_LIST: "STORE_APPLICATION_INSTANCE_LIST",

  TOGGLE_CREATE_APPLICATION_INSTANCE_MODAL: "TOGGLE_CREATE_APPLICATION_INSTANCE_MODAL",
  TOGGLE_INFORMATION_MODAL: "TOGGLE_INFORMATION_MODAL",

  STORE_CURRENT_SELECTED_APPLICATION_INSTANCE: "STORE_CURRENT_SELECTED_APPLICATION_INSTANCE",

  CREATE_NEW_APPLICATION_INSTANCE: "CREATE_NEW_APPLICATION_INSTANCE",

  //  CRUD
  UPDATE_APPLICATION_INSTANCE_INFORMATION: "UPDATE_APPLICATION_INSTANCE_INFORMATION",
  UPDATE_APPLICATION_INSTANCE: "UPDATE_APPLICATION_INSTANCE",
  UPDATE_APPLICATION_INSTANCE_STATUS: "UPDATE_APPLICATION_INSTANCE_STATUS",


};

export const EmployeeActionTypes = {
  REQUEST_FETCH_API: "REQUEST_FETCH_API",
  GET_EMPLOYEE_LIST: "GET_EMPLOYEE_LIST",
  STORE_EMPLOYEE_LIST: "STORE_EMPLOYEE_LIST",

  TOGGLE_CREATE_EMPLOYEE_MODAL: "TOGGLE_CREATE_EMPLOYEE_MODAL",
  TOGGLE_INFORMATION_MODAL: "TOGGLE_INFORMATION_MODAL",

  STORE_CURRENT_SELECTED_EMPLOYEE: "STORE_CURRENT_SELECTED_EMPLOYEE",

  ASSIGN_EMPLOYEE_INTO_PROJECT: "ASSIGN_EMPLOYEE_INTO_PROJECT",

  //  CRUD
  UPDATE_EMPLOYEE_INFORMATION: "UPDATE_EMPLOYEE_INFORMATION",
  CREATE_NEW_EMPLOYEE: "CREATE_NEW_EMPLOYEE",

};

export const ProfileActionTypes = {
  REQUEST_FETCH_API: "REQUEST_FETCH_API",
  GET_PROFILE_LIST: "GET_PROFILE_LIST",
  STORE_PROFILE: "STORE_PROFILE",

  TOGGLE_CREATE_PROFILE_MODAL: "TOGGLE_CREATE_PROFILE_MODAL",
  TOGGLE_INFORMATION_MODAL: "TOGGLE_INFORMATION_MODAL",
  //  LOGIN 
  LOGIN: "LOGIN",
  REQUEST_RESET_PASSWORD: "REQUEST_RESET_PASSWORD",
  CHANGE_PASSWORD: "CHANGE_PASSWORD",

  //  TOGGLE PROFILE PAGE
  TOGGLE_PROFILE_COMPONENT: "TOGGLE_PROFILE_COMPONENT",

};
